#+TITLE: The best way to teach others Emacs
#+DATE: 2015-11-07
#+SETUPFILE: ~/4gamers.cn/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: Emacs
#+JEKYLL_TAGS: Emacs
#+JEKYLL_PUBLISHED: true

安利 Emacs 的正确方式：

第一步：找到一个对 Emacs 真正感兴趣的人。（这是最难的一步）

第二步：让他把 Emacs 自带的教程看完（C-h t），并且给他们一些 Youtube 视频教程。

第三步：让他放弃学习 Emacs，并且安利他去学习 Vim。

第四步：等上十来年。

第五步：十来年后，此 Vim 党想重新尝试 Emacs 了，而且这一次他懂得自己去找资料学习了。

第六步：终于，他成功学会了 Emacs，而你什么也没干。

2333333

上面的段子来自 reddit：

https://www.reddit.com/r/emacs/comments/3r1z7p/in_your_experience_what_was_the_best_way_to_teach/

{{{more}}}

那到底我们（Emacser）要不要安利呢？ 这是一个问题。

另外，什么样的安利姿势才是正确的呢？

** 不要在安利的时候说 Emacs 可以做任何事情。
没错，Emacs 就是一个操作系统，它可以完成任何事情！

map(#[%](str % 千万不要对一个没有入 Emacs 党的人过早地透露这个秘密), [但是，但是，但是])。（重要的事情说三遍）。

我曾经试图这样做，但是，不管我说什么，他们总能找到反驳我的理由。

我说 Emacs 也可以打造成 Python IDE。（你这个有 PyCharm 牛比吗？不能调试打断点吧，哈哈。）

我说 Emacs 也可以打造成 C/C++的 IDE。（你这个有 VS 牛比吗？VS 是世界上最好的 IDE！）

我说 Emacs 还可以煮咖啡！！！（你妹！你煮给我看看！！）擦。。

所以，下次安利的时候不要再对人说 Emacs 可以做任何事情了。

** 不要安利对方快捷键使用和无鼠标操作方式
下次安利 Emacs 的时候，请让他用鼠标！请让他用上下左右键！只有 Vim 党才会宣称 hjkl 比上下左右好使，全键盘流是效率最高的，
我们需要的是肌肉记忆。

（没错，上面说的我全部赞同，并且我也是一个资深的 Vim 党。）

但是，如果他是一个 资深 Vim 党，你千万不能给他安利 Emacs，原因你懂的。而其它编辑器党都是喜欢并且离不开鼠标的。

Emacs 支持鼠标操作，而且也鼓励使用鼠标。比如菜单选择，Minor mode 关闭都可以用鼠标来操作。

另外，不要传达出 Emacs 快捷键很虐人的信号，比如 Ctrl 键到死。。。（事实上也确实如此）

多介绍 which-key 和 hydra，鼓吹 helm 和 ido 的操作方式，让他放弃学习 Emacs 的原生快捷键。

** 要安利 Emacs 是一个编程平台
Emacs 是一个非常好玩的 Lisp 运行时，而且 Emacs Lisp 非常有趣。只有你用了才能体会 Happy Hacking 的乐趣，并且你有可能会乐
此不疲。

看完《 The little scheme 》，你会深刻理解程序递归是什么。然后，你会中括号毒，然后你会想玩 Clojure。然后，就一
发不可收拾了。

另外，Emacs 是一种生活方式。

你试过用 Org mode 做 GTD 来管理你的时间吗？（[[https://github.com/zilongshanren/Spacemacs-rocks/issues/2][Spacemacs Rocks(2): 使用 Org-mode 做 GTD · Issue #2 · zilongshanren/Spacemacs-rocks]])

你试过直接在 Emacs 里面运行终端模式器，然后在此模拟器里面输入 vim .emacs 来修改你的 emacs 配置里面的 bug 吗？

你试过在 Emacs 里面使用 IRC 和收发邮件吗？

Emacs 是一个操作系统，只是它缺少一个好用的编辑器。

不过现在 Spacemacs 打开了新的局面，你们（Vim 党和其它党）准备好了吗？
