#+TITLE: 21 天学会 Emacs（下）
#+DATE: 2016-08-21
#+SETUPFILE: ~/4gamers.cn/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: Emacs
#+JEKYLL_TAGS: Emacs
#+JEKYLL_PUBLISHED: true

TL;DR

21 天学会 Emacs 系列完美收官，你们再也不用追网剧了，我再也不用被人追着更新啦！

{{{more}}}

** 引子
去年十月份开始，我断断续续地录制了 10 集 Spacemacs Rocks，很快就收到了很多人的反馈，要求录制一些新手视频。
（估计是我的 Emacs 操作闪瞎了很多人的双眼。。。）

我当时就立了一个 Flag，说在下一季视频中会有的。后面开始录第二季的第一集的时候，我又给自己挖了一个大坑，
给这个系列取了一个很“响亮”的名字：21 天学会 Emacs。(其实我根本不需要录制 21 集这么多，10 集足够了。。唉，失策。。。)

5 个月后，21 天系列终于被我憋出来了。虽然视频是全部录制完成了，但是由于录制时间的仓促和准备时间不足，
所以难免存在一些缺陷和不足。比如对新手不够友好，视频时间顺序安排不够合理，每集视频的时长安排也不够合理等等。

这篇文章，我准备写一个总结，给非 Vim/Emacs 党，Vim 党和 Emacs 新手党提供一些观看视频的指导。

也算是亡羊补牢吧。

 但是，在学习之前，你一定要有学习的欲望，所以强烈推荐大家观看我录制的 Spacemacs Rocks 第一季的视频。

视频地址： http://list.youku.com/albumlist/show?id=26137579&ascending=1&page=1

** 非 Vim/Emacs 党学习路径
这里的“非 Vim/Emacs 党”，我指的是使用 IDE 和其它一些文本编辑器（Atom，Sublime，Notepad，VS Code）写代码的程序员。

这些同学，其实很多人已经对 IDE 依赖很强了，突然要学习一个上古神器的使用，其实还是有一点压力和难度的。

推荐这些同学，先花一周时间学习一点 Vim 的基础知识和命令行操作（git，shell等）。先理解 Window/Buffer等概念，因为在
Vim 和 Emacs 里面，这些概念跟你平时使用的其它编辑器是有差别的。（我读书少，你别骗我。。我是来学习 Emacs 的。。）

Vim 的学习曲线一开始是非常陡的，建议一周时间学习完 Vimtutor，能够使用 Vim 在终端里面打开一个文件，编辑，保存，然后正确退出即可。

学习 Vim 有助于你在今后学习 Emacs 的时候理解一些基本概念，因为两个神器出现的时期都差不多，有不少概念还是相通的。

之后，可以观看第二季视频的：1-7，如果你不想使用 Vim 的按键，第 7 个视频也可以不看。之后，你可以观看 18-21 的视频即可。

如果你和我一样也喜欢 Vim 的按键，推荐你从头到尾观看完所有的视频。（第 8 天的视频除外）

这里面有1个误区，因为视频已经全部录制完成了，所以你很容易一天看好几个视频。其实这样对你帮助并不大，你需要在观看完一集视频之后，
跟着视频去动手操作，另外，需要认真阅读我在视频里面推荐的延伸阅读材料。切记不要一口气看完前 10 集，然后感觉啥也没学到。。。

** Vim 党学习路径
如果你是一个资深的 Vim 党，学习 Emacs 也是手到擒来的。因为我本人就是一个有着 5 年 Vim 使用经验的资深 Vim 党。

对于 Vim 党而言，最高效的学习方式是观看我的视频 1-7（这里也可以不看视频，直接看社区维护的电子书，目前只更新到了第 7 天）。
然后阅读完 Emacs Tutor，Learn x in y minutes: elisp 教程和 Evil 的 manual。

此时，你对于 Emacs 和 Evil 已经有一定的了解了，可以开始尝试把配置全部迁移到 Spacemacs，然后熟悉 Spacemacs 的按键和配置。
这时候，你的手上已经有一个更好用的 Vim 了，你只需要每天不断地使用，然后遇到不爽的地方稍微 hack 一下，或者去论坛提问跟大家交流。

最后，你可以把视频的 18-21 的视频看完即可。

对于 Vim 党要学习 Emacs，强烈推荐使用 Spacemacs。而且要认真阅读 Spacemacs 自带的文档和 FAQ，这个对于学习怎么使用 Spacemacs 来说太重要了。

** Emacs 新手党学习路径
这里的 “Emacs 新手党”，我指的是那些学习之，放弃之，再学习之，再放弃之的同学，还有学了一点点皮毛而且工作中也不怎么使用 Emacs 的同学。

这部分同学对 Emacs 可以说是“想说爱你不容易”。。。我最早开始学习 Emacs 的时候也有一段比较长的平台期，感觉迟迟没有入门。

这都是正常的，放宽心态即可。使用 Emacs 要达到如鱼得水的地步，认真学习 Emacs Lisp 肯定是必须的，而且要对 Lisp 写代码有激情。

推荐这部分同学，可以暂时不用看我的视频，认真去研习 Introduction To Elisp 内容，至少先看完 1-5 章。

如果有兴趣学习 Spacemacs，可以观看一下我的视频的第 11-14 集，也可以直接阅读 Spacemacs 的官方文档。因为此时看视频，可能对于已经有经验的
Emacs 党来说，时间投入产出比不是很高。但这也不意味着看我的视频完全没有任何帮助。要看你是一个主动学习型，还是一个被动学习型的人啦。

Emacs 新手党需要一份高手的配置，需要一点耐心去学习 Elisp，然后在平时不断地使用 Emacs（写代码，写文档，写博客，GTD 等）。

** 总结
最后，我在我的博客上会把 21 天视频的每一集的大纲简单说明一下，大家可以点击 [[https://zilongshanren.com/LearnEmacs/][LearnEmacs]] 版块去查看，这样有助于大家提前知道视频的主要内容，
不致于浪费时间观看一些对自己价值不大的内容。

最后的最后，欢迎大家加入 emacs-china 社区，多多参与 21 天学会 Emacs 的电子书的编写，为今后的同学学习 Emacs 提供一些帮助。

这样我们这个世界又会因为你的一个小小的举动变得更加美好啦。
