#+TITLE: 最近读过的好书
#+DATE: 2015-09-05
#+SETUPFILE: ~/4gamers.cn/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 读书
#+JEKYLL_TAGS: 读书 笔记
#+JEKYLL_PUBLISHED: true

本文主要记录我近两个月来阅读非技术书籍的心得。

其实我已经有很长一段时间没有阅读非技术书籍了， 一方面可能是自己想在技术方面更精进一些，这两年我专注的点都在
具体的技术上。 另一方面，可能也是时间关系。

不过，这两个月我居然能够看完 7 本非技术书籍，而且看书的大部分时间是周末和晚上睡觉前 2 小时。这对我而言可以说是一个巨大的进步。

这次我挑选了 7 本跟互联网相关的书籍，因为毕竟是互联网从业人员。

这七本书分别是《周鸿祎自述－－我的互联网方法论》，《浪潮之巅》上下两册，《乔布斯传》，《程序员的呐喊》，《异类》和《从 0 到 1 》。

{{{more}}}

** 周鸿祎自述－－我的互联网方法论
看红衣教主的书，通常内心都是比较澎湃的。虽然我自己对 360 的很多产品并无爱，但是看教主的书收获还是蛮多的。
正如书名所表达的，教主在讲述他的互联网方法论。全书里面充满了“免费”，“体验为王”，“用户至上”，“颠覆式创新”，“微创新”等词汇。
这也是近几年来，在各种媒体上能够看到的耳熟能详的词汇。

对于书里面的大部分观点我是比较认同的，但是惟独一点“用户至上”，我觉得有点名不副实。360 号称是一家专注于安全的公司，但是表现出来的很多却是
绑架用户，杀毒软件变成了用户电脑上最大的流氓软件。我曾经有一段时间宁愿电脑裸奔也不愿意安装 360 的任何一款软件。因为只要你安装一个，立马赠送一个
全家桶。现在“百度全家桶”可能更牛逼了。不过幸好我已 5 年不用 Windows，真是万幸。

回想当时 3Q 大战的时候，我还在读研究生，不过当时我居然可以同时运行他们两家的产品，也真是神奇。当时 360 的股价貌似很高（我不炒股，所以不知道具体是多少，
不过出了那么多风头，应该是很高啦。）， 不过现在好像股价已经腰斩了。在移动互联网的风口上，360 除了手机助手还行，我目前还没看到啥东西。

360 当时是威风八面，到处树敌，腾讯，金山，百度都要搞它。现代商业竞争已经不是零和游戏了，合作共赢才是主旋律。况且后面还曝出 360 的杀毒引擎造假，可见 360 在技术上
并没有优势，也无法靠此形成垄断。后来金山也学习它搞免费并且和腾讯等安全厂商联合起来对抗 360。而 360 靠所谓的安全游览器，想在搜索上面和百度分一杯羹。但是表现出来的意思，
好像是要干掉百度一样。这样百度知道“狼来了”，结果可想而知。

360 像一条鲶鱼，给行业带来了活力。打破了一些陈旧的行业规则，最终给用户带来了利益。或许从这个角度来说，360 是一家值得记住的公司。

** 浪潮之巅

** 乔布斯传

** 程序员的呐喊

** 异类

** 从 0 到 1

** 总结
