#+TITLE: 这些年伴随我的一些好习惯
#+DATE: 2015-11-23
#+SETUPFILE: ~/4gamers.cn/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: programming life
#+JEKYLL_TAGS: programming life
#+JEKYLL_PUBLISHED: true

本文我试图回顾一下这些年伴随我的一些好习惯，我会按照我认为的重要性来排序。
坚持这些好习惯，让我在程序员生涯的开端保持不错的势头并且它们还将继续助力我不断进步。

{{{more}}}

** 每天坚持学习 1-2 小时
从毕业至今，工作之外，我几乎每天都会保持 1-2 小时的阅读和学习。
我会利用碎片时间来阅读别人的博客和一些写得不错的文章，通常这不会占据我太多的时间。
我主要的时间都花在阅读经典技术书籍和技术教程上面。

比如前些年我经常逛的 [[http://www.raywenderlich.com/][Ray Wenderlich | Tutorials for iPhone / iOS Developers and Gamers]]

比如最近我在阅读的 [[http://learnopengl.com/][Learn OpenGL, extensive tutorial resource for learning Modern OpenGL]]

这些都是不错的学习资料，非常适合初学者。当阅读完这些教程后，我会挑选一些经典技术书籍来深入研究。

这个过程中，当然是要不断地练习，一方面可以帮助理解知识，另一方面也可以积累编码经验。

** 坚持阅读英文资料
这个习惯是我在大二的时候就坚持下来的，取得的收益非常大。目前我的阅读基本上只限于英文资料，而且我的听力
已经可以达到不看字幕学习 MOOC 的境界。有时候甚至 Youtube 提速 1.5 倍都毫无压力，这个真的是常年积累的结果。

而且英文感觉上来以后，我发现自己在使用 Google 的时候都更加得心应手了，更容易搜索到自己想要的东西。

而且同样是阅读技术资料，我明显感觉自己现在比 4 年前更容易吸收这些知识。而且我觉得中国程序员跟美国程序员的差距
最大的就是英语了。学好英语，真的是刻不容缓。

** 不断改进自己的工具箱
我在以前的文章中写到了我是一个技术 Geek，我喜欢折腾工具，改进工具和工作流，不断提高自己的效率。

从 Vim 到 Emacs,我一刻也没有停止折腾的步伐。在折腾的过程中，我熟练掌握了命令行工具和正则表达式，并且接触了函数式
编程，这些都让我变成了一个更好的程序员。

** 积极融入社区
目前我已退出很多 Q 群和微信群，我几乎不用百度，我也很少逛知乎。

目前我每天必看 Reddit 和 RSS。我也在 Stackoverflow 上面回答问题, 我也时不时上 Google+去提问和交流。

Github 是我每天必须要上的，而且我的所有的代码都托管在上面。

通过写博客来记录自己的所思，所想和所学，扩大自己的圈子，结交更多的朋友。

** 小结
有了这些好的习惯，接下来要做的就是坚持了，目前我 focus 的重点是 3D Graphics，两年后，我再来分享一下我的学习心
得。
