#+TITLE: 关于写博客的一些思考
#+DATE: 2015-11-15
#+SETUPFILE: ~/4gamers.cn/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: Blog
#+JEKYLL_TAGS: Blog
#+JEKYLL_PUBLISHED: true

我最早在 Cocos2D 圈子里面被大家认识是通过写博客，而“子龙山人”这个名号也是自那时起百度便可以搜索到了。

通过写博客，我还认识了与我合作第一本书的作者王寒，认识了泰然网的教主 Iven，认识了带我入 Emacs 教的“一叶道长”，
认识了我的 Boss--Cocos2D-X 创始人王哲。而且后来，我也因此进入了现在的 Cocos2D-X 团队做游戏引擎研发。

总之，写博客有很多收获，也认识了很多朋友（这个是最重要的）。通过和这些认识的朋友交流与合作，我感觉自己明显进步
不了不少。

本文主要介绍我这四年来写博客的一些思考，当然，我不是想安利大家都来写博客。我更想谈的是，写博客应该写些什么以及
如何坚持写博客。

{{{more}}}

** 写博客到底写些什么
写博客最怕写成流水帐或者转载大全。写什么东西很关键，没东西写，那肯定坚持不下来。我中间也一度有一段时间没有坚持
下来，纠其原因，也是我没有系统地思考和规划过这件事情。最近半年来，我几乎每周都会写一篇博客，而且一篇博客的书写
时间大概在 1-2 小时之间。

当然，我目前的文章可能教程和入门型的东西少了很多。以前因为喜欢看我教程的朋友，估计会有点不开心了。不过，我写
博客是为了记录与分享我的编程人生，为什么要为了迎合一部分人的口味而去刻意为之呢？我手写我口，我觉得这是每一个写博客的人应该
有的态度。

好了，不扯远了，接下来我会谈四点我认为比较有价值的，可以拿来写博客的素材。

*** 可以是翻译看过的好文章
这是最简单而且最容易开始写博客的一种方式。通过翻译一些优秀国外技术文章，一方面可以深化自己对于文章的理解，另一
方面，也可以传播知识。我最早就是这么开始写博客的，而且事实上，这种博客还是相当受欢迎的。因为老外的技术文章一般
都写得比较用心，只要你的翻译水准还行，肯定是会受到大家喜欢的。

不过这里需要注意几点，不是随便什么文章都适合拿来翻译的。老外也不是谁都可以写出深入浅出的好文章的。在决定翻译一
个人的文章之前，自己必须是他的博客的老读者了，而且通过阅读博主写的大量文章已经获益很多。此时，你是迫切希望跟大
家一起分享这些文章的。如果你达到了这一步，那么赶紧开工吧。

如果硬要我给出好文章的标准，看看[[http://www.raywenderlich.com/][Ray Wenderlich | Tutorials for iPhone / iOS Developers and Gamers]] 这个网
站上面的文章吧。

*** 可以是读书笔记和心得体会
身处在 IT 行业的码农们，大部分都是爱学习的。其原因，一部分是为了现有的工作，还有很大一部分原因可能是为了接下来我们将会迎接的编程
挑战（当然这些挑战都是意淫的，比如 GO 语言很不错，我以后想转后端。再比如大数据很牛比，我要学习 R，以备将来使用。）
程序员天生有危机意识，而且喜欢过早优化，所以，上面的例子实则每个人在某一段时间可能都出现过。

我们会经常看一些技术书籍和文章，如果这些内容得不到应用，过了一段时间很可能你就会忘记它们。
如果这样反复几次，很多原来爱学习的小伙伴就会变得不那么爱学习了（年龄越大越是如此）--反正也用不上，何必学呢。于是乎，我们身边突然之间多了
一大群一年可能都不看一本技术书籍的同学。

如果是为了给自己充电，一定要记录一些学习笔记。当然，更好的方式可能是做一个 side project。不过如果有文字能够记录
下来是最好不过的了。

这里的心得体会可能是读完一本书之后的，与人交往的，工作上的等等。

人的思绪总是来的快，去的也快。如果有一些想法了，也不要急于马上写成博客。可以先记录下来，然后专门存放在一个地方。
过一段时间，等有空的时候，可以翻出来看看。随着时间的推移，你对之前的想法可能会有偏差，回顾的时候是一个自我蜕变
的过程。

记录心得体会其实有时候也挺为难的，因为有些话可能不太适合在公开场合说。尤其是一些对人或对事的看法之类的，但是，
还是那句话，只要不是恶意的人身攻击，就事论事，我觉得是没啥好顾忌的。

*** 可以是攻克难题的步骤和答案
我们每天都在用 Google 来解决问题，从别人的博客或者 SO 上面的回答来获取方案和灵感，甚至很多程序员可能离开网络都写不
出代码来了。其实，善于利用网络也没啥不好，谁的脑子也记不住所有的东西。

但是，我们一味索取的时候，是否想过贡献呢？有时候，我们查找了 N 多资料，把官方手册和论坛都刷了一遍，可能还是找不
到答案。而且 SO 上面的回答也没有一个是最佳的。你通过几天时间终于解决问题了，你是否会把你的解决方案和过程也分享出
去呢？

*** 可以是自己已经熟练掌握了的东西
大家看到以前我学会 Cocos2D 之后，通过翻译大量优秀教程来“安利”大家学习 Cocos2D。

后来，我学习了一段时间 Vim，而且我感觉我已经 Feel Good 了，我又通过录视频，写教程来“安利”大家学习 Vim。

现在我的 Emacs 水平也很不错了，大家又发现我在“安利”Emacs 了。。。

“子龙。。。能不能停止安利的步伐。。。”

其实写自己熟悉了的东西是最好写的。因为你熟悉，所以你写出来的东西才会条理更清晰，而且更容易引起大家共鸣。

其实还有很多东西可以写，我这里就不一一列举了。坚持写点什么，你总能收获一些东西。

** 如何坚持写博客
知道写什么以后，接下来关键就是坚持了。

*** 写你感兴趣的并且真正热爱的东西。
这一点真的是非常非常非常重要。如果你写的是一些你压根不喜欢的东西，你是不可能写出好文章来的。
当你真正热爱一样东西以后，你就会想尽一切办法去学习和了解它，自然而然，你的素材多了，就更容易写出好文章来了。

*** 控制好写博客的频率
写博客的频率也很重要，一周一篇是目前比较适合我的频率。

*** 找一个称手的写博客工具或平台
比如我的最爱是 Emacs + Hexo + Org + Git，然后我会用 Org GTD 记录一些博客灵感，然后在写博客之前看这些灵感，然后形成文章。
关于我是怎么使用 Emacs 来写博客的，大家可以看看这个[[http://v.youku.com/v_show/id_XMTM4NzIyMTc0MA==.html][使用 Org Mode 来写博客]]


** 总结
让我们一直这样愉快地写下去吧。
